INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(1,'Can add log entry',1,'add_logentry')
,(2,'Can change log entry',1,'change_logentry')
,(3,'Can delete log entry',1,'delete_logentry')
,(4,'Can view log entry',1,'view_logentry')
,(5,'Can add permission',2,'add_permission')
,(6,'Can change permission',2,'change_permission')
,(7,'Can delete permission',2,'delete_permission')
,(8,'Can view permission',2,'view_permission')
,(9,'Can add group',3,'add_group')
,(10,'Can change group',3,'change_group')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(11,'Can delete group',3,'delete_group')
,(12,'Can view group',3,'view_group')
,(13,'Can add user',4,'add_user')
,(14,'Can change user',4,'change_user')
,(15,'Can delete user',4,'delete_user')
,(16,'Can view user',4,'view_user')
,(17,'Can add content type',5,'add_contenttype')
,(18,'Can change content type',5,'change_contenttype')
,(19,'Can delete content type',5,'delete_contenttype')
,(20,'Can view content type',5,'view_contenttype')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(21,'Can add session',6,'add_session')
,(22,'Can change session',6,'change_session')
,(23,'Can delete session',6,'delete_session')
,(24,'Can view session',6,'view_session')
,(25,'Can add user role',7,'add_userrole')
,(26,'Can change user role',7,'change_userrole')
,(27,'Can delete user role',7,'delete_userrole')
,(28,'Can view user role',7,'view_userrole')
,(29,'Can add check in',8,'add_checkin')
,(30,'Can change check in',8,'change_checkin')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(31,'Can delete check in',8,'delete_checkin')
,(32,'Can view check in',8,'view_checkin')
,(33,'Can add dish',9,'add_dish')
,(34,'Can change dish',9,'change_dish')
,(35,'Can delete dish',9,'delete_dish')
,(36,'Can view dish',9,'view_dish')
,(37,'Can add edit component',10,'add_editcomponent')
,(38,'Can change edit component',10,'change_editcomponent')
,(39,'Can delete edit component',10,'delete_editcomponent')
,(40,'Can view edit component',10,'view_editcomponent')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(41,'Can add edit history',11,'add_edithistory')
,(42,'Can change edit history',11,'change_edithistory')
,(43,'Can delete edit history',11,'delete_edithistory')
,(44,'Can view edit history',11,'view_edithistory')
,(45,'Can add meal',12,'add_meal')
,(46,'Can change meal',12,'change_meal')
,(47,'Can delete meal',12,'delete_meal')
,(48,'Can view meal',12,'view_meal')
,(49,'Can add rating',13,'add_rating')
,(50,'Can change rating',13,'change_rating')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(51,'Can delete rating',13,'delete_rating')
,(52,'Can view rating',13,'view_rating')
,(53,'Can add reporting',14,'add_reporting')
,(54,'Can change reporting',14,'change_reporting')
,(55,'Can delete reporting',14,'delete_reporting')
,(56,'Can view reporting',14,'view_reporting')
,(57,'Can add restaurant',15,'add_restaurant')
,(58,'Can change restaurant',15,'change_restaurant')
,(59,'Can delete restaurant',15,'delete_restaurant')
,(60,'Can view restaurant',15,'view_restaurant')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(61,'Can add added dish rating',16,'add_addeddishrating')
,(62,'Can change added dish rating',16,'change_addeddishrating')
,(63,'Can delete added dish rating',16,'delete_addeddishrating')
,(64,'Can view added dish rating',16,'view_addeddishrating')
,(65,'Can add added rating',17,'add_addedrating')
,(66,'Can change added rating',17,'change_addedrating')
,(67,'Can delete added rating',17,'delete_addedrating')
,(68,'Can view added rating',17,'view_addedrating')
,(69,'Can add customer check in',18,'add_customercheckin')
,(70,'Can change customer check in',18,'change_customercheckin')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(71,'Can delete customer check in',18,'delete_customercheckin')
,(72,'Can view customer check in',18,'view_customercheckin')
,(73,'Can add restaurant component reporting',19,'add_restaurantcomponentreporting')
,(74,'Can change restaurant component reporting',19,'change_restaurantcomponentreporting')
,(75,'Can delete restaurant component reporting',19,'delete_restaurantcomponentreporting')
,(76,'Can view restaurant component reporting',19,'view_restaurantcomponentreporting')
,(77,'Can add restaurant reporting',20,'add_restaurantreporting')
,(78,'Can change restaurant reporting',20,'change_restaurantreporting')
,(79,'Can delete restaurant reporting',20,'delete_restaurantreporting')
,(80,'Can view restaurant reporting',20,'view_restaurantreporting')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(81,'Can add review',21,'add_review')
,(82,'Can change review',21,'change_review')
,(83,'Can delete review',21,'delete_review')
,(84,'Can view review',21,'view_review')
,(85,'Can add review reply reporting',22,'add_reviewreplyreporting')
,(86,'Can change review reply reporting',22,'change_reviewreplyreporting')
,(87,'Can delete review reply reporting',22,'delete_reviewreplyreporting')
,(88,'Can view review reply reporting',22,'view_reviewreplyreporting')
,(89,'Can add review reporting',23,'add_reviewreporting')
,(90,'Can change review reporting',23,'change_reviewreporting')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(91,'Can delete review reporting',23,'delete_reviewreporting')
,(92,'Can view review reporting',23,'view_reviewreporting')
,(93,'Can add warning level',24,'add_warninglevel')
,(94,'Can change warning level',24,'change_warninglevel')
,(95,'Can delete warning level',24,'delete_warninglevel')
,(96,'Can view warning level',24,'view_warninglevel')
,(97,'Can add warning',25,'add_warning')
,(98,'Can change warning',25,'change_warning')
,(99,'Can delete warning',25,'delete_warning')
,(100,'Can view warning',25,'view_warning')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(101,'Can add user level',26,'add_userlevel')
,(102,'Can change user level',26,'change_userlevel')
,(103,'Can delete user level',26,'delete_userlevel')
,(104,'Can view user level',26,'view_userlevel')
,(105,'Can add user edit history confirmation',27,'add_useredithistoryconfirmation')
,(106,'Can change user edit history confirmation',27,'change_useredithistoryconfirmation')
,(107,'Can delete user edit history confirmation',27,'delete_useredithistoryconfirmation')
,(108,'Can view user edit history confirmation',27,'view_useredithistoryconfirmation')
,(109,'Can add user edit history component',28,'add_useredithistorycomponent')
,(110,'Can change user edit history component',28,'change_useredithistorycomponent')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(111,'Can delete user edit history component',28,'delete_useredithistorycomponent')
,(112,'Can view user edit history component',28,'view_useredithistorycomponent')
,(113,'Can add token',29,'add_token')
,(114,'Can change token',29,'change_token')
,(115,'Can delete token',29,'delete_token')
,(116,'Can view token',29,'view_token')
,(117,'Can add restaurant meal',30,'add_restaurantmeal')
,(118,'Can change restaurant meal',30,'change_restaurantmeal')
,(119,'Can delete restaurant meal',30,'delete_restaurantmeal')
,(120,'Can view restaurant meal',30,'view_restaurantmeal')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(121,'Can add restaurant dish',31,'add_restaurantdish')
,(122,'Can change restaurant dish',31,'change_restaurantdish')
,(123,'Can delete restaurant dish',31,'delete_restaurantdish')
,(124,'Can view restaurant dish',31,'view_restaurantdish')
,(125,'Can add reporting type',32,'add_reportingtype')
,(126,'Can change reporting type',32,'change_reportingtype')
,(127,'Can delete reporting type',32,'delete_reportingtype')
,(128,'Can view reporting type',32,'view_reportingtype')
,(129,'Can add reply',33,'add_reply')
,(130,'Can change reply',33,'change_reply')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(131,'Can delete reply',33,'delete_reply')
,(132,'Can view reply',33,'view_reply')
,(133,'Can add custom user',34,'add_customuser')
,(134,'Can change custom user',34,'change_customuser')
,(135,'Can delete custom user',34,'delete_customuser')
,(136,'Can view custom user',34,'view_customuser')
,(137,'Can add contribution type',35,'add_contributiontype')
,(138,'Can change contribution type',35,'change_contributiontype')
,(139,'Can delete contribution type',35,'delete_contributiontype')
,(140,'Can view contribution type',35,'view_contributiontype')
;
INSERT INTO rrs.auth_permission (id,name,content_type_id,codename) VALUES 
(141,'Can add contribution',36,'add_contribution')
,(142,'Can change contribution',36,'change_contribution')
,(143,'Can delete contribution',36,'delete_contribution')
,(144,'Can view contribution',36,'view_contribution')
,(145,'Can add user reporting',37,'add_userreporting')
,(146,'Can change user reporting',37,'change_userreporting')
,(147,'Can delete user reporting',37,'delete_userreporting')
,(148,'Can view user reporting',37,'view_userreporting')
;