# Generated by Django 3.0.7 on 2020-06-17 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantratingapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
