# Generated by Django 3.0.7 on 2020-08-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantratingapi', '0002_auto_20200707_1200'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_restaurant_name'),
        ),
    ]
