# Generated by Django 3.0.7 on 2020-06-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantratingapi', '0003_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('level_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('points_level', models.PositiveIntegerField()),
                ('allocated_comfirmation_points', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField()),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField()),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_level',
                'managed': True,
            },
        ),
    ]
