# Generated by Django 3.0.7 on 2020-06-27 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0004_userlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_status', models.PositiveSmallIntegerField()),
                ('email_code', models.CharField(max_length=255)),
                ('email_verified', models.PositiveSmallIntegerField()),
                ('birthday', models.DateField()),
                ('gender', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(null=True, upload_to='')),
                ('updated_on', models.DateTimeField()),
                ('level_number', models.ForeignKey(db_column='level_number', on_delete=django.db.models.deletion.PROTECT, to='restaurantratingapi.UserLevel')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='restaurantratingapi.UserRole')),
                ('updated_by', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_user',
                'managed': True,
            },
        ),
    ]
