# Generated by Django 3.0.7 on 2020-06-27 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0005_auto_20200627_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_level_reated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_level_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
