# Generated by Django 3.0.7 on 2020-06-27 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0006_auto_20200627_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
