# Generated by Django 3.0.7 on 2020-07-02 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0014_auto_20200702_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'meal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RestaurantMeal',
            fields=[
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='restaurant_meal_meal', serialize=False, to='restaurantratingapi.Meal')),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_meal_created_by', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantratingapi.Restaurant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_meal_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurant_meal',
                'managed': True,
                'unique_together': {('meal', 'restaurant')},
            },
        ),
    ]
