# Generated by Django 3.0.7 on 2020-07-03 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0017_auto_20200703_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDish',
            fields=[
                ('dish', models.ForeignKey(db_column='dish_id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='restaurant_dish_dish', serialize=False, to='restaurantratingapi.Dish')),
                ('status', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(db_column='added_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_dish_added_by', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_dish_restaurant', to='restaurantratingapi.Restaurant')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_dish_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurant_dish',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='restaurantdish',
            constraint=models.UniqueConstraint(fields=('dish_id', 'restaurant_id', 'added_by'), name='unique_restaurant_dish'),
        ),
    ]
