# Generated by Django 3.0.7 on 2020-07-03 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0018_auto_20200703_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='token_created_by', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='token_restaurant', to='restaurantratingapi.Restaurant')),
            ],
            options={
                'db_table': 'token',
                'managed': True,
            },
        ),
    ]
