# Generated by Django 3.0.7 on 2020-07-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantratingapi', '0019_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='token_restaurant', to='restaurantratingapi.Restaurant'),
        ),
    ]
