# Generated by Django 3.0.7 on 2020-07-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantratingapi', '0020_auto_20200703_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='token_restaurant', to='restaurantratingapi.Restaurant'),
        ),
    ]
