# Generated by Django 3.0.7 on 2020-07-03 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0021_auto_20200703_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_value', models.CharField(max_length=255)),
                ('requested_value', models.CharField(max_length=255)),
                ('status', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(db_column='confirmed_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='edit_history_confirmed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'edit_history',
                'managed': True,
            },
        ),
    ]
