# Generated by Django 3.0.7 on 2020-07-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantratingapi', '0022_edithistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditComponent',
            fields=[
                ('component_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('component_name', models.CharField(max_length=255)),
                ('confirmation_point_level', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'edit_component',
                'managed': True,
            },
        ),
    ]
