# Generated by Django 3.0.7 on 2020-07-05 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('restaurantratingapi', '0023_editcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEditHistoryComponent',
            fields=[
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='user_edit_history_component_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('component', models.ForeignKey(db_column='component_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_edit_history_component_component', to='restaurantratingapi.EditComponent')),
                ('history', models.ForeignKey(db_column='history_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_edit_history_component_history', to='restaurantratingapi.EditHistory')),
                ('restaurant', models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_edit_history_component_restaurant', to='restaurantratingapi.Restaurant')),
            ],
            options={
                'db_table': 'user_edit_history_component',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='useredithistorycomponent',
            constraint=models.UniqueConstraint(fields=('user_id', 'history_id', 'restaurant_id', 'component_id'), name='unique_user_edit_history_component'),
        ),
    ]
