# Generated by Django 3.0.7 on 2020-07-05 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0025_auto_20200705_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEditHistoryConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_points', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(db_column='history_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_edit_history_confirmation_history', to='restaurantratingapi.EditHistory')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_edit_history_confirmation_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_edit_history_confirmation',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='useredithistoryconfirmation',
            constraint=models.UniqueConstraint(fields=('user_id', 'history_id'), name='unique_user_edit_history_confirmation'),
        ),
    ]
