# Generated by Django 3.0.7 on 2020-07-05 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0026_auto_20200705_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionType',
            fields=[
                ('contribution_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('contribution_name', models.CharField(max_length=50)),
                ('allocated_points', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contribution_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contribution_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contribution_type',
                'managed': True,
            },
        ),
    ]
