# Generated by Django 3.0.7 on 2020-07-05 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0027_contributiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('contribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('contribution_type', models.ForeignKey(db_column='contribution_type', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contribution_contribution_type', to='restaurantratingapi.ContributionType')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='contribution_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contribution',
                'managed': True,
            },
        ),
    ]
