# Generated by Django 3.0.7 on 2020-07-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantratingapi', '0028_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dish_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('price_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('service_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('verified', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': True,
            },
        ),
    ]
