# Generated by Django 3.0.7 on 2020-07-05 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0029_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedRating',
            fields=[
                ('rating', models.OneToOneField(db_column='rating_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='added_rating_rating', serialize=False, to='restaurantratingapi.Rating')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('restaurant', models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_rating_restaurant', to='restaurantratingapi.Restaurant')),
                ('token_number', models.ForeignKey(blank=True, db_column='token_number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_rating_token', to='restaurantratingapi.Token')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_rating_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'added_rating',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='addedrating',
            constraint=models.UniqueConstraint(fields=('rating', 'restaurant', 'user'), name='unique_added_rating'),
        ),
    ]
