# Generated by Django 3.0.7 on 2020-07-05 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0030_auto_20200705_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedDishRating',
            fields=[
                ('rating', models.OneToOneField(db_column='rating_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='added_dish_rating_rating', serialize=False, to='restaurantratingapi.Rating')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'added_dish_rating',
                'managed': True,
            },
        ),
        migrations.RemoveConstraint(
            model_name='addedrating',
            name='unique_added_rating',
        ),
        migrations.AddField(
            model_name='addeddishrating',
            name='dish',
            field=models.ForeignKey(db_column='dish_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_dish_rating_dish', to='restaurantratingapi.Dish'),
        ),
        migrations.AddField(
            model_name='addeddishrating',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_dish_rating_restaurant', to='restaurantratingapi.Restaurant'),
        ),
        migrations.AddField(
            model_name='addeddishrating',
            name='token_number',
            field=models.ForeignKey(blank=True, db_column='token_number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_dish_rating_token', to='restaurantratingapi.Token'),
        ),
        migrations.AddField(
            model_name='addeddishrating',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_dish_rating_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
