# Generated by Django 3.0.7 on 2020-07-06 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0031_auto_20200705_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rating', models.OneToOneField(db_column='rating_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='review_rating', serialize=False, to='restaurantratingapi.Rating')),
                ('message', models.TextField(blank=True, null=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='')),
                ('upvote_count', models.PositiveIntegerField()),
                ('report_count', models.PositiveIntegerField(db_column='report count')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
                'managed': True,
            },
        ),
    ]
