# Generated by Django 3.0.7 on 2020-07-06 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0032_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_created_by', to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(db_column='rating_id', on_delete=django.db.models.deletion.CASCADE, related_name='reply_rating', to='restaurantratingapi.Rating')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reply',
                'managed': True,
            },
        ),
    ]
