# Generated by Django 3.0.7 on 2020-07-06 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0034_reportingtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('reporting_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('reporter', models.ForeignKey(db_column='reporter', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reporting_type_reporter', to=settings.AUTH_USER_MODEL)),
                ('reporting_type', models.ForeignKey(db_column='reporting_type', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reporting_reporting_type', to='restaurantratingapi.ReportingType')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reporting_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reporting',
                'managed': True,
            },
        ),
    ]
