# Generated by Django 3.0.7 on 2020-07-06 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0036_restaurantcomponentreporting_restaurantreporting_reviewreplyreporting_reviewreporting_userreporting'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningLevel',
            fields=[
                ('warning_level', models.AutoField(primary_key=True, serialize=False)),
                ('warning_level_name', models.CharField(max_length=50)),
                ('allocated_points', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='warning_level_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warning_level_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warning_level',
                'managed': True,
            },
        ),
    ]
