# Generated by Django 3.0.7 on 2020-07-06 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0037_warninglevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('warning_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='warning_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warning_updated_by', to=settings.AUTH_USER_MODEL)),
                ('warning_level', models.ForeignKey(db_column='warning_level', on_delete=django.db.models.deletion.DO_NOTHING, related_name='warning_warning_level', to='restaurantratingapi.WarningLevel')),
            ],
            options={
                'db_table': 'warning',
                'managed': True,
            },
        ),
    ]
