# Generated by Django 3.0.7 on 2020-07-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantratingapi', '0038_warning'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('check_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'check_in',
                'managed': True,
            },
        ),
    ]
