# Generated by Django 3.0.7 on 2020-07-06 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantratingapi', '0039_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCheckIn',
            fields=[
                ('check_in', models.OneToOneField(db_column='check_in_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='customer_check_in_check_in', serialize=False, to='restaurantratingapi.CheckIn')),
                ('restaurant', models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_check_in_restaurant', to='restaurantratingapi.Restaurant')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_check_in_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_check_in',
                'managed': True,
            },
        ),
    ]
