INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can add permission',1,'add_permission')
,('Can change permission',1,'change_permission')
,('Can delete permission',1,'delete_permission')
,('Can view permission',1,'view_permission')
,('Can add group',2,'add_group')
,('Can change group',2,'change_group')
,('Can delete group',2,'delete_group')
,('Can view group',2,'view_group')
,('Can add user',3,'add_user')
,('Can change user',3,'change_user')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can delete user',3,'delete_user')
,('Can view user',3,'view_user')
,('Can add content type',4,'add_contenttype')
,('Can change content type',4,'change_contenttype')
,('Can delete content type',4,'delete_contenttype')
,('Can view content type',4,'view_contenttype')
,('Can add check in',5,'add_checkin')
,('Can change check in',5,'change_checkin')
,('Can delete check in',5,'delete_checkin')
,('Can view check in',5,'view_checkin')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can add dish',6,'add_dish')
,('Can change dish',6,'change_dish')
,('Can delete dish',6,'delete_dish')
,('Can view dish',6,'view_dish')
,('Can add edit component',7,'add_editcomponent')
,('Can change edit component',7,'change_editcomponent')
,('Can delete edit component',7,'delete_editcomponent')
,('Can view edit component',7,'view_editcomponent')
,('Can add edit history',8,'add_edithistory')
,('Can change edit history',8,'change_edithistory')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can delete edit history',8,'delete_edithistory')
,('Can view edit history',8,'view_edithistory')
,('Can add meal',9,'add_meal')
,('Can change meal',9,'change_meal')
,('Can delete meal',9,'delete_meal')
,('Can view meal',9,'view_meal')
,('Can add rating',10,'add_rating')
,('Can change rating',10,'change_rating')
,('Can delete rating',10,'delete_rating')
,('Can view rating',10,'view_rating')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can add reporting',11,'add_reporting')
,('Can change reporting',11,'change_reporting')
,('Can delete reporting',11,'delete_reporting')
,('Can view reporting',11,'view_reporting')
,('Can add restaurant',12,'add_restaurant')
,('Can change restaurant',12,'change_restaurant')
,('Can delete restaurant',12,'delete_restaurant')
,('Can view restaurant',12,'view_restaurant')
,('Can add user role',13,'add_userrole')
,('Can change user role',13,'change_userrole')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can delete user role',13,'delete_userrole')
,('Can view user role',13,'view_userrole')
,('Can add added dish rating',14,'add_addeddishrating')
,('Can change added dish rating',14,'change_addeddishrating')
,('Can delete added dish rating',14,'delete_addeddishrating')
,('Can view added dish rating',14,'view_addeddishrating')
,('Can add added rating',15,'add_addedrating')
,('Can change added rating',15,'change_addedrating')
,('Can delete added rating',15,'delete_addedrating')
,('Can view added rating',15,'view_addedrating')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can add customer check in',16,'add_customercheckin')
,('Can change customer check in',16,'change_customercheckin')
,('Can delete customer check in',16,'delete_customercheckin')
,('Can view customer check in',16,'view_customercheckin')
,('Can add restaurant component reporting',17,'add_restaurantcomponentreporting')
,('Can change restaurant component reporting',17,'change_restaurantcomponentreporting')
,('Can delete restaurant component reporting',17,'delete_restaurantcomponentreporting')
,('Can view restaurant component reporting',17,'view_restaurantcomponentreporting')
,('Can add restaurant reporting',18,'add_restaurantreporting')
,('Can change restaurant reporting',18,'change_restaurantreporting')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can delete restaurant reporting',18,'delete_restaurantreporting')
,('Can view restaurant reporting',18,'view_restaurantreporting')
,('Can add review',19,'add_review')
,('Can change review',19,'change_review')
,('Can delete review',19,'delete_review')
,('Can view review',19,'view_review')
,('Can add review reply reporting',20,'add_reviewreplyreporting')
,('Can change review reply reporting',20,'change_reviewreplyreporting')
,('Can delete review reply reporting',20,'delete_reviewreplyreporting')
,('Can view review reply reporting',20,'view_reviewreplyreporting')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can add review reporting',21,'add_reviewreporting')
,('Can change review reporting',21,'change_reviewreporting')
,('Can delete review reporting',21,'delete_reviewreporting')
,('Can view review reporting',21,'view_reviewreporting')
,('Can add warning level',22,'add_warninglevel')
,('Can change warning level',22,'change_warninglevel')
,('Can delete warning level',22,'delete_warninglevel')
,('Can view warning level',22,'view_warninglevel')
,('Can add warning',23,'add_warning')
,('Can change warning',23,'change_warning')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can delete warning',23,'delete_warning')
,('Can view warning',23,'view_warning')
,('Can add user level',24,'add_userlevel')
,('Can change user level',24,'change_userlevel')
,('Can delete user level',24,'delete_userlevel')
,('Can view user level',24,'view_userlevel')
,('Can add user edit history confirmation',25,'add_useredithistoryconfirmation')
,('Can change user edit history confirmation',25,'change_useredithistoryconfirmation')
,('Can delete user edit history confirmation',25,'delete_useredithistoryconfirmation')
,('Can view user edit history confirmation',25,'view_useredithistoryconfirmation')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can add user edit history component',26,'add_useredithistorycomponent')
,('Can change user edit history component',26,'change_useredithistorycomponent')
,('Can delete user edit history component',26,'delete_useredithistorycomponent')
,('Can view user edit history component',26,'view_useredithistorycomponent')
,('Can add token',27,'add_token')
,('Can change token',27,'change_token')
,('Can delete token',27,'delete_token')
,('Can view token',27,'view_token')
,('Can add restaurant meal',28,'add_restaurantmeal')
,('Can change restaurant meal',28,'change_restaurantmeal')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can delete restaurant meal',28,'delete_restaurantmeal')
,('Can view restaurant meal',28,'view_restaurantmeal')
,('Can add restaurant dish',29,'add_restaurantdish')
,('Can change restaurant dish',29,'change_restaurantdish')
,('Can delete restaurant dish',29,'delete_restaurantdish')
,('Can view restaurant dish',29,'view_restaurantdish')
,('Can add reporting type',30,'add_reportingtype')
,('Can change reporting type',30,'change_reportingtype')
,('Can delete reporting type',30,'delete_reportingtype')
,('Can view reporting type',30,'view_reportingtype')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can add reply',31,'add_reply')
,('Can change reply',31,'change_reply')
,('Can delete reply',31,'delete_reply')
,('Can view reply',31,'view_reply')
,('Can add custom user',32,'add_customuser')
,('Can change custom user',32,'change_customuser')
,('Can delete custom user',32,'delete_customuser')
,('Can view custom user',32,'view_customuser')
,('Can add contribution type',33,'add_contributiontype')
,('Can change contribution type',33,'change_contributiontype')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can delete contribution type',33,'delete_contributiontype')
,('Can view contribution type',33,'view_contributiontype')
,('Can add contribution',34,'add_contribution')
,('Can change contribution',34,'change_contribution')
,('Can delete contribution',34,'delete_contribution')
,('Can view contribution',34,'view_contribution')
,('Can add user reporting',35,'add_userreporting')
,('Can change user reporting',35,'change_userreporting')
,('Can delete user reporting',35,'delete_userreporting')
,('Can view user reporting',35,'view_userreporting')
;
INSERT INTO rrs2.auth_permission (name,content_type_id,codename) VALUES 
('Can add log entry',36,'add_logentry')
,('Can change log entry',36,'change_logentry')
,('Can delete log entry',36,'delete_logentry')
,('Can view log entry',36,'view_logentry')
,('Can add session',37,'add_session')
,('Can change session',37,'change_session')
,('Can delete session',37,'delete_session')
,('Can view session',37,'view_session')
;